services:
  backend:
    build: ./backend-api
    env_file:
      - .env
    ports:
      - "5255:5255"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - database
    volumes:
      - ./backend-api:/app
      - ./backend-api/raspored.db:/app/raspored.db 
    command: dotnet watch run --urls http://0.0.0.0:5255

  frontend:
    build:
      context: ./frontend-app
      target: development
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    working_dir: /app

  database:
    image: nouchka/sqlite3
    volumes:
      - ./database:/data
